# Generated by Django 5.2.16 on 2026-07-17 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='make_id',
            new_name='car_make',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='models_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='model_type',
            new_name='type',
        ),
    ]
